# Generated by Django 2.0.7 on 2018-07-28 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postimages',
            name='post',
        ),
        migrations.RemoveField(
            model_name='postimages',
            name='user',
        ),
        migrations.DeleteModel(
            name='PostImages',
        ),
    ]
